#pragma once

#include <stdbool.h>

#include "sdkconfig.h"

#define APP_NODE_ID CONFIG_APP_NODE_ID
#define APP_HEARTBEAT_INTERVAL_S CONFIG_APP_HEARTBEAT_INTERVAL_S
#define APP_MQTT_BROKER_PORT 1883

#define APP_TOPIC_MAX_LEN 128
#define APP_PAYLOAD_MAX_LEN 384
#define APP_REQUEST_ID_MAX_LEN 64
#define APP_PUBLISH_QUEUE_LENGTH 12
#define APP_PUBLISH_MAX_DATA_LEN 2048
#define APP_IMAGE_CHUNK_SIZE 2048
